[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:postgres]
command=/usr/lib/postgresql/14/bin/postgres -D /var/lib/postgresql/14/main -c config_file=/etc/postgresql/14/main/postgresql.conf
user=postgres
autostart=true
autorestart=true
priority=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:redis]
command=/usr/bin/redis-server --bind 127.0.0.1
autostart=true
autorestart=true
priority=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:kafka]
command=/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties
autostart=true
autorestart=true
priority=2
startsecs=15
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:consumer]
command=/app/venv/bin/python /app/scripts/consume_events.py
directory=/app/scripts
autostart=true
autorestart=true
priority=3
startsecs=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:fastapi]
command=/app/venv/bin/uvicorn main:app --host 0.0.0.0 --port 7860
directory=/app/app
autostart=true
autorestart=true
priority=4
startsecs=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0